name: React Build Action

run-name: Building A React Application

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 20

      - run: npm install
      - run: npm run build
      - run: npm test
